name: Ryans Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List all the files
        run: ls -la

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  test:
      runs-on: ubuntu-latest

      needs: build
  
      steps:
        - uses: actions/checkout@v4
  
        - name: Faked out test
          run: ls -la

  deploy:
      runs-on: ubuntu-latest

      needs: test

      environment: production
  
      steps:
        - uses: actions/checkout@v4
  
        - name: Faked out build
          run: ls -la
